### ISSUE TITLE
Earn forgets configured fees after reload of JAM tab

### ISSUE THREAD

**Issue by RaiqRe** [joinmarket-webui/jam#614] opened 2023-04-20 20:18 UTC
**Expected behavior**
When I configure an Earn offer with non default values, reload the JAM tab and look at the configuration I expect it to be the same as I configured it.

**Actual behavior**
See the expected behavior. Instead of the configuration staying the way I configured it after a reload, it is set back to the default values.

**Steps to reproduce the problem**
  1. Configure the earn service with non default values.
  2. Reload the browser window.
  3. Look at the configuration. It is now set to default values again.

**Specifications**
  - Version: JoinMarket v0.9.9, JAM v0.1.5
  - Platform: MyNode
  - Browser: Chrome

**Additional context**
-

**Comment by theborakompanioni** [comment] 2023-04-21 10:00
Hey @RaiqRe, thanks for the report.

Just tested the stated problem and could not reproduce it (tested on Firefox, Brave and Chromium). Settings are stored in "localstorage" with prefix `jm-` (e.g. `jm-feeRel`, `jm-feeAbs`, `jm-minsize`) and are populated in the form as expected. Do you - by chance - clear all browsing data on exit automatically ("Clear cookies and site data when you close all windows")? This would explain the behaviour you are experiencing.

**Comment by RaiqRe** [comment] 2023-04-21 14:37
I mistakenly wrote that I restarted the browser but I reloaded the JAM tab. Sorry for the confusing. I edited the issue in that way.

**Comment by theborakompanioni** [comment] 2023-04-21 21:14
> I mistakenly wrote that I restarted the browser but I reloaded the JAM tab. Sorry for the confusing. I edited the issue in that way.
> 
> Can you now reproduce the issue?

The values will only be stored to localstorage if you clicked on the submit button at least once. If you never click the button, the values won't get persisted. This is intended behaviour.

**Comment by RaiqRe** [comment] 2023-04-21 21:36
- I go to the Earn tab in JAM. 
- Configure some non default absolute fee. 
- I click on "Start Earning!". 
- I click on "Stop"
- When I expand "Offer options", the non default fee value is still visible.
- When I now reload the JAM browser tab and expand "Offer options" again, the non default value is gone and the it is again at the default value.

It's not really serious. Just something I stumbled upon when I restarted the offer and the fee was not what I was expecting it to be.

**Comment by theborakompanioni** [comment] 2023-04-22 15:03
I am sorry @RaiqRe, I cannot reproduce it. Tested on Chromium Version 112.0.5615.165 (Official Build, ungoogled-chromium) (64-bit). : /
Would it be possible for you to look into the developer tools (F12) in "Storage" and tell whether you see the values being persisted to localstorage?

**Comment by theborakompanioni** [comment] 2023-05-07 16:38
Closing this now. Please reopen if it happens again or you think it should be looked at again.

**Closed by theborakompanioni** 2023-05-07 16:38 UTC
Labels: bug
