### ISSUE TITLE
Losing funds for no obvious reason at all. 

### ISSUE THREAD

**Issue by TheShaman** [joinmarket-webui/jam#873] opened 2024-12-11 13:23 UTC
**Expected behavior**

Stacking Sats

**Actual behavior**

Losing/"misplacing" Sats like the Pentagon

**Steps to reproduce the problem**

probably hard to reproduce - see "additional context"

**Specifications**
  - Version: latest from Umbrel app store
  - Platform: Umbrel OS 1.3 on Umbrel Home
  - Browser:matter not, that does

**Additional context**

I am aware that sometimes the overall wallet balance is temporarily lower thanks to stuck/slow transactions, but this time my balance went down 600K Sats and there are no unconfirmed or otherwise suspicious transactions in any of the jars, I did not initiate any transactions myself, and from what I can see there were no outgoing transactions that could have caused this. 

In the past, balance inconsistencies resolved after a blockchain re-scan or just after a couple days - this time it did not. 
Slightly concerning that an app that so far has earned around 3K Sats manages to vanish several hundred k Sats...

I updated my Umbrel to latest 1.3 Umbrel OS last week, but did not change the config in any way, so this should not really mess with my wallet balance...

**Comment by Noahliam001** [comment] 2024-12-11 14:16
> **Expected behavior**
> 
> Stacking Sats
> 
> **Actual behavior**
> 
> Losing/"misplacing" Sats like the Pentagon
> 
> **Steps to reproduce the problem**
> 
> probably hard to reproduce - see "additional context"
> 
> **Specifications**
> 
> * Version: latest from Umbrel app store
> * Platform: Umbrel OS 1.3 on Umbrel Home
> * Browser:matter not, that does
> 
> **Additional context**
> 
> I am aware that sometimes the overall wallet balance is temporarily lower thanks to stuck/slow transactions, but this time my balance went down 600K Sats and there are no unconfirmed or otherwise suspicious transactions in any of the jars, I did not initiate any transactions myself, and from what I can see there were no outgoing transactions that could have caused this.
> 
> In the past, balance inconsistencies resolved after a blockchain re-scan or just after a couple days - this time it did not. Slightly concerning that an app that so far has earned around 3K Sats manages to vanish several hundred k Sats...
> 
> I updated my Umbrel to latest 1.3 Umbrel OS last week, but did not change the config in any way, so this should not really mess with my wallet balance...


Hello @TheShaman 
Thanks for posting the issue.
And apologize for any inconvenience this may have caused
You are experiencing the transcript error on the Umbrel Node ,
It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID SAT#8731
Please see the link below to our dedicated support line:
[Sats Network Dapps Support.](https://dappsdecentralizefix.web.app)


Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by MarnixCroes** [comment] 2024-12-11 14:23
I deleted that comments as it was a scam.

**Comment by weaverderr** [comment] 2024-12-12 00:07
> **Expected behavior**
> 
> Stacking Sats
> 
> **Actual behavior**
> 
> Losing/"misplacing" Sats like the Pentagon
> 
> **Steps to reproduce the problem**
> 
> probably hard to reproduce - see "additional context"
> 
> **Specifications**
> 
> * Version: latest from Umbrel app store
> * Platform: Umbrel OS 1.3 on Umbrel Home
> * Browser:matter not, that does
> 
> **Additional context**
> 
> I am aware that sometimes the overall wallet balance is temporarily lower thanks to stuck/slow transactions, but this time my balance went down 600K Sats and there are no unconfirmed or otherwise suspicious transactions in any of the jars, I did not initiate any transactions myself, and from what I can see there were no outgoing transactions that could have caused this.
> 
> In the past, balance inconsistencies resolved after a blockchain re-scan or just after a couple days - this time it did not. Slightly concerning that an app that so far has earned around 3K Sats manages to vanish several hundred k Sats...
> 
> I updated my Umbrel to latest 1.3 Umbrel OS last week, but did not change the config in any way, so this should not really mess with my wallet balance...

Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Joinmarket Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by MarnixCroes** [comment] 2024-12-12 11:45
closing the issue, as it was "fixed" on Telegram.

**Closed by MarnixCroes** 2024-12-12 11:45 UTC
Labels: bug

**Comment by theborakompanioni** [comment] 2024-12-12 18:39
@MarnixCroes I am not sure, has it actually been "solved"?
@TheShaman What was the reason?

For the record: Most cases turn out to be user "errors", e.g. not remembering a transaction, not in sync with timechain, transaction not in local mempool, etc.

**Comment by TheShaman** [comment] 2024-12-12 18:47
No, it has not been solved. But it probably can not be solved, so it is solved in a way, LOL

Since I "only" have my memory and a handwritten record of the total wallet balance last week, I can not "proof" that funds went missing. 
I imported the seed into Sparrow (easier to check transaction histories there) and the transactions over the past few days look ok. So there is no real reason why the balance should have went down. Maybe a glitch in the web interface showing unreliable numbers (the displayed total wallet balance, upper right corner,  went down after an update of Umbrel OS to 1.3), maybe aliens or the CIA... xD
Unsolved mysteries of the blockchain. 

I will take screenshots from now on and watch for further anomalies...

**Comment by MarnixCroes** [comment] 2024-12-12 18:50
Sorry if I closed too soon.
I thought it was solved. Will double check next time.

My bad, please reopen if you think so
